### PR TITLE
Clearing url cache on db deletion

### PR DESCRIPTION
**Pull request by monishsyed**
When a migration issue occurs in DB and the old db is deleted, clearing out the URL cache to make sure that the UA feed loads perfectly

### CODE REVIEW

**Comment by rlepinski** [comment]
The inbox database migrations only store metadata about the inbox messages while the URL cache stores the actual content about the inbox messages. I don't how a migration affects the URL cache. When we fetch the inbox messages again it will be pointing to the same body, so the cached content should still be valid. If it changes the last-modified cache control will take affect and we will fetch the latest content.

Are you seeing issues that this resolves?

**Comment by monishsyed** [comment]
@rlepinski What i'm seeing is that when i update my app from from a UA 4.x to 5.0, the coredata migration fails and the UA library attempts to delete the old db file and create a new one. Since the new one doesn't have any meta data for the already existing cached data, the UA throws a HTTP/1.1 304 Not Modified and UA inbox doesn't seem to return any feeds cards. Clearing the cache when this occurs makes it load all the feeds again.

**Comment by rlepinski** [comment]
Yeah, that sounds like a problem. However we do not use the UAURLProtocol for the last modified time for inbox fetches. The UAURLProtocol is only used to cache the content of inbox message bodies. We need to delete https://github.com/urbanairship/ios-library-dev/blob/master/Airship/Inbox/UAInboxAPIClient.m#L43 instead.

**Comment by monishsyed** [comment]
@rlepinski Sorry for the late response. Thanks for pointing out the correct solution. I have made the corrections and pushed my changes. Can you take a look please ?

**Comment by jkolb** [comment]
The UAURLProtocol cache does still cause problems after a lost CoreData database. Because the URL's are stored in the cache they generate "If-Modified-Since" headers for those messages which prevents them from being retrieved after losing the database. Even if this wasn't true there is no reason to keep this cache around after a failed database migration since it refers to data that is now out of sync with reality.

**Comment by rlepinski** [comment]
Only the message bodies are cached with the UAURLProtocol, the metadata about the messages are stored in our database. When you pull down the messages again, the url bodies will not changes so fetching them from the cache is perfectly valid. It will cause no harm.

**Comment by rlepinski** [comment]
@monishsyed This looks good, however things have significantly changed in the next release where this will not work. A ticket has been filed and it will be addressed.

**Comment by monishsyed** [comment]
@rlepinski looking forward for the next release.

**Pull request closed without merging**
