### PR TITLE
Added support for building the AirshipKit framework with carthage.

### PR DESCRIPTION
**Pull request by spenrose**
- Shared the Framework scheme
- Use the AirshipLib project to build instead of just linking to the static library

### CODE REVIEW

**Comment by marc-scig** [comment]
Hey @spenrose,

Thanks for the PR. We're not terribly familiar with Carthage, do you think you could speak to what motivated this and how it would help with integration?

A little bit of background – the AirshipKit project is really just an end-user distribution mechanism for the embedded framework, to get around some of the difficulties associated with universal builds. Since we don't actually distribute source code in our canonical releases I'm a little hesitant to make a change like this, but we'd like to work with you to adress your needs as best we can.

**Comment by jwilson-rodale** [comment]
Perhaps, I can shed some light on it as well.  Carthage is a relatively new dependency manager for building Mac/iOS frameworks.  It leverages the dynamic framework that Apple released with iOS 8.0.  It's really nice because it will look for a "shared" schema in your Xcode project in the GitHub repository.  It will pull the code and build the framework based on that shared schema.  You can then drag and drop the framework into your project.  Carthage gives you the ability to point to a tag or branch within the designated repo.

The alternative dependency manager that is more popular is Cocoa Pods.  You can pull various 3rd party libraries for it and Cocoa Pods will generate its own Xcode project and workspace so you can manage Open Source/Private libraries.  Carthage is far less invasive.  It doesn't touch any Xcode projects and leaves it up to you to manually add the frameworks to your Xcode project.  This less invasive technique has led to its rise in popularity and a lot of 3rd party libraries now support Carthage as well as Cocoa Pods.

I would like to see Carthage support as well.  If I could avoid adding the airship library to my Xcode project and just add the framework it is much easier since I deal with so many 3rd party dependencies.  Please let me know if I can shed anymore light on Carthage.

**Comment by jwilson-rodale** [comment]
Just to add to the above commentary.  I grabbed @spenrose branch and used Carthage to build it.

I already have Carthage installed.
I added this line to my Cartfile:
github "WeConnect/ios-library" "feature/carthage"

I ran "carthage update" in the terminal and it grabbed the latest commit from his branch (feature/carthage) and built AirshipKit.framework with no errors.  Dragged and dropped the framework into my Xcode project.  I was able to successfully use the framework to send push notifications.

**Comment by spenrose** [comment]
Thanks for adding all that info @jwilson-rodale

**Comment by filipeteixeira83** [comment]
I also use Carthage, would be nice to have official support.

**Comment by walsht** [comment]
+1

**Comment by crow** [comment]
The shared scheme necessary for carthage support has been added.

**Comment by filipeteixeira83** [comment]
:clap: 

Good news, thanks guys!

**Comment by walsht** [comment]
@crow 
*** Checking out ios-library at "7.0.2"
Parse error: expected submodule commit SHA in ls-tree output:

**Comment by crow** [comment]
Updated the release tag, should work now on both master and 7.0.2. Thanks for catching this.

**Pull request closed without merging**
