### PR TITLE
Get rid of @synchronized to prevent code from getting into deadlocks …

### PR DESCRIPTION
**Pull request by adc-amatosov**
…because of different order of nested @synchronized calls

### CODE REVIEW

**Comment by rlepinski** [comment]
@adc-amatosov I like the changes you made but I am not sure if any of the code you touched actually has a potential for a deadlock. Did you have any issues with the current SDK version?

Also, please sign a [contribution agreement](https://docs.urbanairship.com/contribution-agreement/). Thanks!

**Comment by brblakley** [comment]
@rlepinski I just posted an issue that describes what I’m experiencing. I’m not sure if it’s related but it sounds like it could be. 

https://github.com/urbanairship/ios-library/issues/137

**Comment by adc-amatosov** [comment]
@brblakley yes, this is one of the deadlocks we had.
We had 2 more deadlocks at initialization stages.
 1. While trying to update tags right after initialization
 2. Randomly at app startup
 3. Constantly at app startup if user allowed push previously (described in #137), but was reproducible only on select devices, but with 100% probability on them.

**Comment by rlepinski** [comment]
@brblakley You can reproduce 100% on some devices? Could you test out this PR and make sure it fixes your problem.

Clearly we have a deadlock somewhere and this will most likely prevent it. @adc-amatosov Once I get the contribution agreement we can merge and work on a patch release.

**Comment by adc-amatosov** [comment]
Ok @rlepinski 
I am working on CLA. Is this the right one https://docs.urbanairship.com/contribution-agreement/?

**Comment by rlepinski** [comment]
@adc-amatosov Yep, thats the one

**Comment by BrianBatchelder** [comment]
@adc-amatosov : you're using `dispatch_once` in several places (UAInboxDBManager & UADisposable) where it can't be used, because, according to [Apple](https://developer.apple.com/documentation/dispatch/1447169-dispatch_once): 

> The predicate must point to a variable stored in global or static scope. The result of using a predicate with automatic or dynamic storage (including Objective-C instance variables) is undefined.

Another good discussion can be found [here](https://www.cocoanetics.com/2012/02/threadsafe-lazy-property-initialization/). 

Did you track down problems to these specific files? If so, do you have alternate solutions?

**Comment by robinkunde** [comment]
@BrianBatchelder I wrote an explanation of the specific deadlock I encountered, plus alternate solutions [here](https://github.com/urbanairship/ios-library/issues/137#issuecomment-316103858).

**Comment by rlepinski** [comment]
@adc-amatosov We fixed UAInboxDBManager and did a slightly different change to UAChannelRegistrar. I believe the deadlocks have been addressed. Some of your other changes are still fine so if you want to rebase your PR we are happy to take a look.

**Comment by adc-amatosov** [comment]
Hi @BrianBatchelder. Thanks for pointing out to issue with dispatch_once in GCD, I was not aware of it. I was assuming it is as good as std/boost call_once, but it is obviously not.
We didn't have issues with that code. I was just optimizing out all `@synchronize` calls out of it.

**Comment by rlepinski** [comment]
Closing this PR for now. Please reopen with a rebased branch if you want to get some of your other changes in.

**Pull request closed without merging**
