### PR TITLE
Added #pragma to silence UIAlertView warning in iOS 8 and beyond

### PR DESCRIPTION
**Pull request by grosch**

### CODE REVIEW

**Comment by rlepinski** [comment]
Does this work with the UA_SUPPRESS_UI_DEPRECATION_WARNINGS macro?

**Comment by grosch** [comment]
No clue what that is.  Shouldn't require us to implement debug flags though that we likely don't know about.  When the library can do it directly....

**Comment by rlepinski** [comment]
I guess I should of phrased that differently...

We defined a macro to conditionally suppress deprecations  `UA_SUPPRESS_UI_DEPRECATION_WARNINGS` in our UI code. Could you see if that macro works instead of explicitly ignoring the warning for the one line?

**Comment by rlepinski** [comment]
Nvm, looks like that is only for the "Push" classes. This is fine how it is.

**Comment by rlepinski** [comment]
Thanks!

**Comment by grosch** [comment]
I’m not sure how you want me to test.  If I define that myself it conflicts with the definition in UACommon.h

Your macro won’t effect that anyways though because your header doesn’t use that pragma.

**Pull request merged**
